version: "3.9"

services:
  backend:
    image: locally-backend
    container_name: locally_backend
    restart: always
    command: >
      sh -c "
        until PGPASSWORD=$DB_PASSWORD pg_isready -h \"$DB_HOST\" -p \"$DB_PORT\" -U \"$DB_USER\"; do
          echo 'Waiting for Postgres...';
          sleep 2;
        done;
        npx prisma generate &&
        npx prisma migrate deploy &&
        npm run start:prod
      "
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
